### ISSUE TITLE
Headless Ubuntu 22.04 not showing tty1 on boot

### ISSUE THREAD

**Issue by vibhoregit** [lcdwiki/LCD-show-ubuntu#18]
So I'll be clear from the beginning, I am using headless ubuntu server 22.04 on a rpi 4 model. I want the rpi to show tty1 (default terminal) on boot up on the LCD screen but so far I have gotten only white LCD screen (and black screen output on HDMI). I have tested with gnome desktop and that works with the LCD but not the headless system. Is there a way to display tty1 on LCD screen (like how it usually displays on a HDMI display even with headless systems).  I am using a 3.5 inch rev A LCD.

**Comment by vibhoregit** [comment]
Okay found the solution. Edit /boot/firmware/cmdline.txt (Make a backup before editing!) and add `fbcon=map:10` at the end of line. Then ensure PI IS NOT CONNECTED TO HDMI!! Do a reboot and done!

**Comment by acorrow** [comment]
HUGE Upvote, idk why I didn't look for issues sooner. Been beating my head against a wall on this for a day....

**Comment by is-paranoia** [comment]
@vibhoregit Hi! Could you share your files: /boot/config.txt , /boot/firmware/cmdline.txt and /boot/firmware/config.txt? Followed your instructions on Raspberry Pi 4B (Ubuntu server 22.4) and the screen is still white( Thanks!

**Comment by vibhoregit** [comment]
@is-paranoia 
[cmdline.txt](https://github.com/lcdwiki/LCD-show-ubuntu/files/11877441/cmdline.txt)
[config.txt](https://github.com/lcdwiki/LCD-show-ubuntu/files/11877442/config.txt)
These are all the files I have since the Pi is not with me any more

**Comment by samiibnjamil** [comment]
Hello,
 How did you get it to work with Ubuntu 24.04? are there any instruction for Ubuntu 24.04 for this display?  I am stuck at white screen both for my RPI5 and 4

**Comment by vibhoregit** [comment]
@samiibnjamil I have not tried it with Ubuntu 24.04, You can try following the same process as I did earlier by editing the /boot/firmware/cmdline.txt. The config and cmdline files are attacehed above for your reference.
